### PR TITLE
It works

### PR DESCRIPTION
**Pull request by marcingrzejszczak**

### CODE REVIEW

**Comment by gerganishteto** [comment]
Hi Marcin,

I have merged your changes however without this dependency: 

dependencyManagement {
 -     imports {
 -          mavenBom 'org.springframework.cloud:spring-cloud-netflix:1.3.0.M1'
 -     }
 -}

OneplatformSampleGiftcardconsumerApplication is not compiling because of @EnableRetry annotation which requires spring-retry. 

However after I add the necessary depedency for compilation the tests still does not work for me :( 
Can you check whether you have pushed all of your changes?

017-02-20 15:16:55.920  INFO 13536 --- [           main] c.netflix.config.ChainedDynamicProperty  : Flipping property: oneplatform-sample-giftcard.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2017-02-20 15:16:55.923  INFO 13536 --- [           main] c.n.l.DynamicServerListLoadBalancer      : DynamicServerListLoadBalancer for client oneplatform-sample-giftcard initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=oneplatform-sample-giftcard,current list of Servers=[localhost:12325],Load balancer stats=Zone stats: {unknown=[Zone:unknown;	Instance count:1;	Active connections count: 0;	Circuit breaker tripped count: 0;	Active connections per server: 0.0;]
},Server stats: [[Server:localhost:12325;	Zone:UNKNOWN;	Total Requests:0;	Successive connection failure:0;	Total blackout seconds:0;	Last connection made:Thu Jan 01 02:00:00 EET 1970;	First connection made: Thu Jan 01 02:00:00 EET 1970;	Active Connections:0;	total failure count in last (1000) msecs:0;	average resp time:0.0;	90 percentile resp time:0.0;	95 percentile resp time:0.0;	min resp time:0.0;	max resp time:0.0;	stddev resp time:0.0]
]}ServerList:org.springframework.cloud.contract.stubrunner.spring.cloud.ribbon.StubRunnerRibbonServerList@e76aa
2017-02-20 15:16:56.133  INFO 13536 --- [io-12325-exec-6] o.a.c.c.C.[Tomcat-1].[localhost].[/]     : RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
2017-02-20 15:16:56.172 ERROR 13536 --- [io-12325-exec-6] WireMock                                 : Request was not matched:
{
  "url" : "/v1/purchases/invalid",
  "absoluteUrl" : "http://localhost:12325/v1/purchases/invalid",
  "method" : "GET",
  "clientIp" : "127.0.0.1",
  "headers" : {
    "accept" : "application/json, application/*+json",
    "content-type" : "application/json;charset=UTF-8",
    "accept-charset" : "big5, big5-hkscs, cesu-8, euc-jp, euc-kr, gb18030, gb2312, gbk, ibm-thai, ibm00858, ibm01140, ibm01141, ibm01142, ibm01143, ibm01144, ibm01145, ibm01146, ibm01147, ibm01148, ibm01149, ibm037, ibm1026, ibm1047, ibm273, ibm277, ibm278, ibm280, ibm284, ibm285, ibm290, ibm297, ibm420, ibm424, ibm437, ibm500, ibm775, ibm850, ibm852, ibm855, ibm857, ibm860, ibm861, ibm862, ibm863, ibm864, ibm865, ibm866, ibm868, ibm869, ibm870, ibm871, ibm918, iso-2022-cn, iso-2022-jp, iso-2022-jp-2, iso-2022-kr, iso-8859-1, iso-8859-13, iso-8859-15, iso-8859-2, iso-8859-3, iso-8859-4, iso-8859-5, iso-8859-6, iso-8859-7, iso-8859-8, iso-8859-9, jis_x0201, jis_x0212-1990, koi8-r, koi8-u, shift_jis, tis-620, us-ascii, utf-16, utf-16be, utf-16le, utf-32, utf-32be, utf-32le, utf-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-big5-hkscs-2001, x-big5-solaris, x-euc-jp-linux, x-euc-tw, x-eucjp-open, x-ibm1006, x-ibm1025, x-ibm1046, x-ibm1097, x-ibm1098, x-ibm1112, x-ibm1122, x-ibm1123, x-ibm1124, x-ibm1166, x-ibm1364, x-ibm1381, x-ibm1383, x-ibm300, x-ibm33722, x-ibm737, x-ibm833, x-ibm834, x-ibm856, x-ibm874, x-ibm875, x-ibm921, x-ibm922, x-ibm930, x-ibm933, x-ibm935, x-ibm937, x-ibm939, x-ibm942, x-ibm942c, x-ibm943, x-ibm943c, x-ibm948, x-ibm949, x-ibm949c, x-ibm950, x-ibm964, x-ibm970, x-iscii91, x-iso-2022-cn-cns, x-iso-2022-cn-gb, x-iso-8859-11, x-jis0208, x-jisautodetect, x-johab, x-macarabic, x-maccentraleurope, x-maccroatian, x-maccyrillic, x-macdingbat, x-macgreek, x-machebrew, x-maciceland, x-macroman, x-macromania, x-macsymbol, x-macthai, x-macturkish, x-macukraine, x-ms932_0213, x-ms950-hkscs, x-ms950-hkscs-xp, x-mswin-936, x-pck, x-sjis_0213, x-utf-16le-bom, x-utf-32be-bom, x-utf-32le-bom, x-windows-50220, x-windows-50221, x-windows-874, x-windows-949, x-windows-950, x-windows-iso2022jp",
    "user-agent" : "Java/1.8.0_101",
    "host" : "localhost:12325",
    "connection" : "keep-alive"
  },
  "cookies" : { },
  "browserProxyRequest" : false,
  "loggedDate" : 1487596616145,
  "bodyAsBase64" : "",
  "body" : "",
  "loggedDateString" : "2017-02-20T13:16:56Z"
}
Closest match:
{
  "url" : "/health",
  "method" : "GET"
}
2017-02-20 15:16:56.906  INFO 13536 --- [erListUpdater-0] c.netflix.config.ChainedDynamicProperty  : Flipping property: oneplatform-sample-giftcard.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2017-02-20 15:17:23.986 ERROR 13536 --- [io-12325-exec-8] WireMock                                 : Request was not matched:
{
  "url" : "/v1/purchases/valid",
  "absoluteUrl" : "http://localhost:12325/v1/purchases/valid",
  "method" : "GET",
  "clientIp" : "127.0.0.1",
  "headers" : {
    "accept" : "application/json, application/*+json",
    "content-type" : "application/json;charset=UTF-8",
    "accept-charset" : "big5, big5-hkscs, cesu-8, euc-jp, euc-kr, gb18030, gb2312, gbk, ibm-thai, ibm00858, ibm01140, ibm01141, ibm01142, ibm01143, ibm01144, ibm01145, ibm01146, ibm01147, ibm01148, ibm01149, ibm037, ibm1026, ibm1047, ibm273, ibm277, ibm278, ibm280, ibm284, ibm285, ibm290, ibm297, ibm420, ibm424, ibm437, ibm500, ibm775, ibm850, ibm852, ibm855, ibm857, ibm860, ibm861, ibm862, ibm863, ibm864, ibm865, ibm866, ibm868, ibm869, ibm870, ibm871, ibm918, iso-2022-cn, iso-2022-jp, iso-2022-jp-2, iso-2022-kr, iso-8859-1, iso-8859-13, iso-8859-15, iso-8859-2, iso-8859-3, iso-8859-4, iso-8859-5, iso-8859-6, iso-8859-7, iso-8859-8, iso-8859-9, jis_x0201, jis_x0212-1990, koi8-r, koi8-u, shift_jis, tis-620, us-ascii, utf-16, utf-16be, utf-16le, utf-32, utf-32be, utf-32le, utf-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-big5-hkscs-2001, x-big5-solaris, x-euc-jp-linux, x-euc-tw, x-eucjp-open, x-ibm1006, x-ibm1025, x-ibm1046, x-ibm1097, x-ibm1098, x-ibm1112, x-ibm1122, x-ibm1123, x-ibm1124, x-ibm1166, x-ibm1364, x-ibm1381, x-ibm1383, x-ibm300, x-ibm33722, x-ibm737, x-ibm833, x-ibm834, x-ibm856, x-ibm874, x-ibm875, x-ibm921, x-ibm922, x-ibm930, x-ibm933, x-ibm935, x-ibm937, x-ibm939, x-ibm942, x-ibm942c, x-ibm943, x-ibm943c, x-ibm948, x-ibm949, x-ibm949c, x-ibm950, x-ibm964, x-ibm970, x-iscii91, x-iso-2022-cn-cns, x-iso-2022-cn-gb, x-iso-8859-11, x-jis0208, x-jisautodetect, x-johab, x-macarabic, x-maccentraleurope, x-maccroatian, x-maccyrillic, x-macdingbat, x-macgreek, x-machebrew, x-maciceland, x-macroman, x-macromania, x-macsymbol, x-macthai, x-macturkish, x-macukraine, x-ms932_0213, x-ms950-hkscs, x-ms950-hkscs-xp, x-mswin-936, x-pck, x-sjis_0213, x-utf-16le-bom, x-utf-32be-bom, x-utf-32le-bom, x-windows-50220, x-windows-50221, x-windows-874, x-windows-949, x-windows-950, x-windows-iso2022jp",
    "user-agent" : "Java/1.8.0_101",
    "host" : "localhost:12325",
    "connection" : "keep-alive"
  },
  "cookies" : { },
  "browserProxyRequest" : false,
  "loggedDate" : 1487596643961,
  "bodyAsBase64" : "",
  "body" : "",
  "loggedDateString" : "2017-02-20T13:17:23Z"
}
Closest match:
{
  "url" : "/health",
  "method" : "GET"
}

**Comment by marcingrzejszczak** [comment]
You can downgrade and use some other version of Netflix

**Comment by marcingrzejszczak** [comment]
Ah and btw check this out - https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/master/consumer_with_discovery

**Comment by gerganishteto** [comment]
Okay so I did small changes and now the code with your changes works.
I started to check what has been mapped at http://localhost:8090/__admin/

It seems that whenever I have the stubs installed locally in the user\.m2 repo it is being picked up over the one specified with the property repositoryRoot ="classpath:m2repo/repository".

So basically I had to delete the stubs jar from the Maven local repo in order StubRunner to start picking the rights stubs from repositoryRoot ="classpath:m2repo/repository".

So it seems that the problem is with the UID pattern and I will have to dig a little bit more to understand what is the problem there.

I also checked your example at https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/master/consumer_with_discovery. It is working :)
So now I just have to manage to make my example working in order to convince people that we can use Spring Cloud Contracts in our company :)

Thanks a lot for the support.

By the way when do you plan to release a stable version of 1.1.0.BUILD-SNAPSHOT of Spring Cloud Contracts?

**Comment by marcingrzejszczak** [comment]
> By the way when do you plan to release a stable version of 1.1.0.BUILD-SNAPSHOT of Spring Cloud Contracts?

You can use the M1 from Dalston.M1 release.

> So it seems that the problem is with the UID pattern and I will have to dig a little bit more to understand what is the problem there.

I can tell you what the problem is. The JSON from WireMock has that `ID` field. That's why your results are wrong

**Comment by gerganishteto** [comment]
Hi Marcin,

Still strugging ... Do you have any idea why in my case in the generated json mappings I have id and UID which contains the same value and in your demo projects (for instance in the beerproducer) after the build is run you do not have this id field in the generated json mappings.

**Example:**

  _"mappings" : [ {
    **"id" : "8dbd6ba7-17c8-402d-bd5a-38dcfedb51c4"**,
    "request" : {
      "urlPattern" : "v1/purchases/AaaAaAAa-7e3D-EDbA-BcAa-C5A7FEff6a8b",
      "method" : "GET",
      "headers" : {
        "Content-Type" : {
          "matches" : "application/json.*"
        }
      }
    },
    "response" : {
      "status" : 200,
      "body" : "{\"transactionStatus\":\"APPROVED\",\"transactionDate\":\"7461-21-32T09:45:24Z\",\"amount\":1,\"giftCard\":{\"name\":\"name\",\"cardNumber\":1,\"duration\":\"0\"}}",
      "headers" : {
        "Content-Type" : "application/json"
      }
    },
    **"uuid" : "8dbd6ba7-17c8-402d-bd5a-38dcfedb51c4"**
  }_

**Comment by marcingrzejszczak** [comment]
I have no idea. They should be there only in the WireMock stub, not the body. That's really strange. Maybe you're using some old version of WireMock or sth. That's really strange. Try removing the `id` and `uuid` from stubs maybe? You're the only person to have this problem so nothing fast comes to my mind.

**Comment by gerganishteto** [comment]
Hi,

I have pushed new changes in the project. The thing is that when PurchaseConsumerController lookup operation works with String id value the tests pass and when I change the type of the parameter to UUID WireMock cannot match the requests.  Weird, isn't it?

You can check also the jar with the stubs. I have just replaced the valid/invalid strings with UUID values and also I have altered the tests in the code.

**Comment by marcingrzejszczak** [comment]
Yeah that's strange. I don't know what the problem is ATM. You can maybe check out https://github.com/spring-cloud-samples/spring-cloud-contract-samples and see if you're doing sth in a different way?

**Comment by gerganishteto** [comment]
Hi again, 

I have found the problem and now I feel stupid :D http://stackoverflow.com/questions/8258480/type-of-character-generated-by-uuid

6.5.4 Software generating the hexadecimal representation of a UUID shall not use upper case letters. NOTE – It is recommended that the hexadecimal representation used in all human-readable formats be restricted to lower-case letters. Software processing this representation is, however, required to accept both upper and lower case letters as specified in 6.5.2.

> The Java documentation for the UUID class’ toString method documents in BNF that uppercase is allowed when generating a string, in contradiction to the UUID standard specification. However the actual behavior of the class and its toString method in the Oracle implementation for Java 8 is correct, using lowercase for output but tolerating either uppercase or lowercase for input.

**Input in either lower-/uppercase:**

```
UUID uuidFromLowercase = UUID.fromString ( "897b7f44-1f31-4c95-80cb-bbb43e4dcf05" ); 
UUID uuidFromUppercase = UUID.fromString ( "897B7F44-1F31-4C95-80CB-BBB43E4DCF05" );
Output to lowercase only:

System.out.println ( "uuidFromLowercase.toString(): " + uuidFromLowercase );
System.out.println ( "uuidFromUppercase.toString(): " + uuidFromUppercase );
uuidFromLowercase.toString(): 897b7f44-1f31-4c95-80cb-bbb43e4dcf05

uuidFromUppercase.toString(): 897b7f44-1f31-4c95-80cb-bbb43e4dcf05
```

And I was using uppercase also in my contracts that's why the example was not working with UUID :((((

Anyway thanks a lot for the time spent with me to make it work! 
I really appreciate your help.

**Comment by marcingrzejszczak** [comment]
haha! That's amazing :D Great stuff that you've found this out. Really great job and thanks for sharing how you found out what the problem was :)

**Pull request merged**
